modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="additionalweapon"
version="${file.jarVersion}"
displayName="Additional Weapon"
logoFile="additionalweapon.png"
credits="Thanks for this example mod goes to Java"
authors="Timeless Keeper"
description='''
This mod add additional weapons using the Better Combat mod. It's inspire by the Medieval Weapon mod and the Spartan Weaponry mod.
'''

[[dependencies.additionalweapon]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.additionalweapon]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
